name: Run unit tests

on:
    push:
        branches-ignore:
            - master

jobs:
    build:
        strategy:
            matrix:
                platform: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: npm install and test
              run: |
                  npm install
                  tsc --noEmit
                  npm run test
